import NavBar from "@/components/NavBar";
import ThemeProvider from "@/components/Theme";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../styles/globals.css'; 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alfred AI",
  description: "Generated by Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider>
       <div className="bg-white w-full dark:bg-slate-800"><NavBar/>
        {children}</div> </ThemeProvider></body>
    </html>
  );
}
